[package]
name = "purg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
reqwest = {version = "0.11", features = ["blocking"]}
serde_json = "1.0.59"
chrono = "0.4.*"
glsl = "6.0.0"